import { SaleItem } from './models/saleitem.model'

export const SALEITEMS: SaleItem[] = [
  new SaleItem(30796, 159, "LOU SLIM - RAW SELVEDGE", "Made from 12.5 oz narrow loom Japanese Selvedge and superfluous dark indigo dye, the Raw Selvedge is a 21st Century jean that pays homage to the origins of denim. The Raw Selvedge denim is perfectly showcased in our slim straight Lou fit, which was inspired by the jeans that Lou Reed wore while recording Velvet Underground’s eponymous LP in 1966.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/lou_slim_pant_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/lou_slim_pant_alt.jpg", "pant", 1),
  new SaleItem(32284, 149,"IGGY SKINNY - PERFECTO", "Based on the style worn by the Godfather of Punk himself, the Iggy Skinny is a regular waist and slim leg skinny inspired by the iconic era of rock and roll. With a comfort stretch and yarn dyed black warp and weft, the Iggy Skinny - Perfecto is a no-nonsense, hard-wearing and incredibly comfortable black jean. We’re sure it will become your favourite pair.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/iggy_skinny_pant_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/iggy_skinny_pant_alt.jpg", "pant", 0),
  new SaleItem(32851, 69,"NOISE TEE - TEENAGE RIOT", "The Noise Tee is a regular fit crew tee, crafted with quality sub textured cotton for comfortable, relaxed silhouette. It features our signature grin stitch and seasonal \"Teenage Riot\" graphic printed on the front.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/noise_tee_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/noise_tee_alt.jpg", "tee", 1),
  new SaleItem(32817, 89,"UNITY TEE - NAVY LINEN STRIPE", "The Unity Tee combines the natural characters of cotton and linen with a patterned navy stripe. This classic tee features a regular fitting silhouette and crew neckline with capped sleeves. Try it partnered with your favourite denim wash with white trainers.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/unity_tee_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/unity_tee_alt.jpg", "tee", 0),
  new SaleItem(32811, 199,"TYPE ONE JACKET - BEATEN INDIGO", "The Type One Jacket in Beaten Indigo features a slim fitting silhouette in premium indigo fabric. It's stone-washed appearance gives it that worn-in look with distressed detailing throughout. Silver metal hardware and button up front with front and side pockets.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/type_one_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/type_one_jacket_alt.jpg", "jacket", 1),
  new SaleItem(32769, 649,"RIDER JACKET - BLACK LEATHER", "A black leather jacket is one of the most timeless wardrobe essentials around and the Rider Jacket in black leather is famed for it's high quality rider style and statement antique silver zips. Crafted from premium Arabian lamb leather the rider has a zip front closure, pointed collar and side pockets with minimal styling.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/rider_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/rider_jacket_alt.jpg", "jacket", 1),
];
