import { SaleItem } from './models/saleitem.model'

export const SALEITEMSMENS: SaleItem[] = [
  new SaleItem(30796, 159, "LOU SLIM - RAW SELVEDGE", "Made from 12.5 oz narrow loom Japanese Selvedge and superfluous dark indigo dye, the Raw Selvedge is a 21st Century jean that pays homage to the origins of denim. The Raw Selvedge denim is perfectly showcased in our slim straight Lou fit, which was inspired by the jeans that Lou Reed wore while recording Velvet Underground’s eponymous LP in 1966.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/lou_slim_pant_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/lou_slim_pant_alt.jpg", "", "pant", 1),
  new SaleItem(32284, 149,"IGGY SKINNY - PERFECTO", "Based on the style worn by the Godfather of Punk himself, the Iggy Skinny is a regular waist and slim leg skinny inspired by the iconic era of rock and roll. With a comfort stretch and yarn dyed black warp and weft, the Iggy Skinny - Perfecto is a no-nonsense, hard-wearing and incredibly comfortable black jean. We’re sure it will become your favourite pair.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/iggy_skinny_pant_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/iggy_skinny_pant_alt.jpg", "", "pant", 0),
  new SaleItem(32851, 69,"NOISE TEE - TEENAGE RIOT", "The Noise Tee is a regular fit crew tee, crafted with quality sub textured cotton for comfortable, relaxed silhouette. It features our signature grin stitch and seasonal \"Teenage Riot\" graphic printed on the front.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/noise_tee_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/noise_tee_alt.jpg", "", "tee", 1),
  new SaleItem(32817, 89,"UNITY TEE - NAVY LINEN STRIPE", "The Unity Tee combines the natural characters of cotton and linen with a patterned navy stripe. This classic tee features a regular fitting silhouette and crew neckline with capped sleeves. Try it partnered with your favourite denim wash with white trainers.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/unity_tee_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/unity_tee_alt.jpg", "", "tee", 0),
  new SaleItem(32811, 199,"TYPE ONE JACKET - BEATEN INDIGO", "The Type One Jacket in Beaten Indigo features a slim fitting silhouette in premium indigo fabric. It's stone-washed appearance gives it that worn-in look with distressed detailing throughout. Silver metal hardware and button up front with front and side pockets.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/type_one_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/type_one_jacket_alt.jpg", "", "jacket", 1),
  new SaleItem(32769, 649,"RIDER JACKET - BLACK LEATHER", "A black leather jacket is one of the most timeless wardrobe essentials around and the Rider Jacket in black leather is famed for it's high quality rider style and statement antique silver zips. Crafted from premium Arabian lamb leather the rider has a zip front closure, pointed collar and side pockets with minimal styling.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/rider_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/rider_jacket_alt.jpg", "", "jacket", 1),
];

export const SALEITEMSWOMENS: SaleItem[] = [
  new SaleItem(37837, 189, "MARILYN SKINNY - BLUE BUST", "As the affinity for skinny-leg jeans continues, invest in the Marilyn Skinny, our iconic high waisted jean with a skinny, tapered leg profile that was inspired by Marilyn Monroe. Blue Bust features premium European fabric with a beautiful mid blue wash with ripped kneehole destruction and raw detailing for an edgy finish.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/marilyn_skinny_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/marilyn_skinny_alt.jpg", "", "pant", 1),
  new SaleItem(37662, 179, "BOWERY SKINNY - TRUE BLACK", "The Bowery Skinny is our mid rise skinny jean, crafted in a premium European stretch fabric with high stretch and retention the Bowery in true black features stay black technology for a longer, richer wash. Wear them paired back with a tee or a tucked in blouse and box-fresh trainers for an effortless approach.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/bowery_skinny_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/bowery_skinny_alt.jpg", "", "pant", 1),
  new SaleItem(37813, 199, "MADEN JACKET - BEATEN BLUE", "Maden Jacket in Beaten Blue exudes understated cool with distressing detail for a raw finish. It's crafted to a loose shape and features a button-up-front with chest pockets and is framed with a classic point collar. Wear yours with a white tee and your favourite denim wash to mirror the understated aesthetic.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/maden_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/maden_jacket_alt.jpg", "", "jacket", 0),
  new SaleItem(37745, 299, "NAME", "The Isabel Jacket presents an oversized, tailored silhouette with subtle feminine undertones. It's crafted from a textured wool blend fabric with outside front welt pockets, front button closure, a fully lined interior and is framed with a classic V neckline. Team it with any denim wash and a white tee for head-to-toe impact.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/isabel_jacket_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/isabel_jacket_alt.jpg", "", "jacket", 1),
  new SaleItem(37751, 79, "LOVE ME TEE", "Crafted in luxurious linen the Love me Tee features a comfortable, relaxed fit perfect for day-to-day wear. Featuring custom embroidered detailing at neck and capped sleeves.", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/_alt.jpg", "", "type", 0),
  new SaleItem(37730, 89, "PANEL TEE", "Crafted from a cotton blend the Panel Tee features front and back panels and a self bound neck. Perfect for day-to-day wear, simply add your favourite denim wash and white trainers for an effortless approach. ", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/panel_tee_main.jpg", "https://raw.githubusercontent.com/william-chu/epicodus-week8-9/master/src/assets/panel_alt.jpg", "", "type", 1),
];
